<a href="https://colab.research.google.com/github/sadikinisaac/general/blob/master/heartdiseaseprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importing primary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib notebook

In [0]:
# Reading the data 
data = pd.read_csv('https://www.openml.org/data/get_csv/1592290/phpgNaXZe')

In [0]:
# Setting up the column
column = ['sbp','tobacco','ldl','adiposity','famhist','type','obesity','alcohol','age','chd']

In [0]:
data.columns=column

In [5]:
data.head()

sbp  tobacco   ldl  adiposity  famhist  type  obesity  alcohol  age  chd
0  160    12.00  5.73      23.11        1    49    25.30    97.20   52    2
1  144     0.01  4.41      28.61        2    55    28.87     2.06   63    2
2  118     0.08  3.48      32.28        1    52    29.14     3.81   46    1
3  170     7.50  6.41      38.03        1    51    31.99    24.26   58    2
4  134    13.60  3.50      27.78        1    60    25.99    57.34   49    2

In [6]:
data.describe()

sbp     tobacco         ldl  ...     alcohol         age         chd
count  462.000000  462.000000  462.000000  ...  462.000000  462.000000  462.000000
mean   138.326840    3.635649    4.740325  ...   17.044394   42.816017    1.346320
std     20.496317    4.593024    2.070909  ...   24.481059   14.608956    0.476313
min    101.000000    0.000000    0.980000  ...    0.000000   15.000000    1.000000
25%    124.000000    0.052500    3.282500  ...    0.510000   31.000000    1.000000
50%    134.000000    2.000000    4.340000  ...    7.510000   45.000000    1.000000
75%    148.000000    5.500000    5.790000  ...   23.892500   55.000000    2.000000
max    218.000000   31.200000   15.330000  ...  147.190000   64.000000    2.000000

[8 rows x 10 columns]

In [7]:
# Checking for any missing values 
data.isnull().sum()

sbp          0
tobacco      0
ldl          0
adiposity    0
famhist      0
type         0
obesity      0
alcohol      0
age          0
chd          0
dtype: int64

In [0]:
#The values shown are 0, therefore no missing values in the DataFrame

In [0]:
# Feature Scaling, making categorical data precise 
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data['famhist']=encoder.fit_transform(data['famhist'])
data['chd']=encoder.fit_transform(data['chd'])

In [9]:
data.head(5)

sbp  tobacco   ldl  adiposity  famhist  type  obesity  alcohol  age  chd
0  160    12.00  5.73      23.11        0    49    25.30    97.20   52    1
1  144     0.01  4.41      28.61        1    55    28.87     2.06   63    1
2  118     0.08  3.48      32.28        0    52    29.14     3.81   46    0
3  170     7.50  6.41      38.03        0    51    31.99    24.26   58    1
4  134    13.60  3.50      27.78        0    60    25.99    57.34   49    1

In [0]:
from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler(feature_range =(0,100))

In [0]:
# setting scale of max min value for sbp in range of 0-100, normalise
data['sbp'] = scale.fit_transform(data['sbp'].values.reshape(-1,1))

In [12]:
data.head()

sbp  tobacco   ldl  adiposity  ...  obesity  alcohol  age  chd
0  50.427350    12.00  5.73      23.11  ...    25.30    97.20   52    1
1  36.752137     0.01  4.41      28.61  ...    28.87     2.06   63    1
2  14.529915     0.08  3.48      32.28  ...    29.14     3.81   46    0
3  58.974359     7.50  6.41      38.03  ...    31.99    24.26   58    1
4  28.205128    13.60  3.50      27.78  ...    25.99    57.34   49    1

[5 rows x 10 columns]

In [13]:
# Data after modification
data.describe()

sbp     tobacco         ldl  ...     alcohol         age         chd
count  462.000000  462.000000  462.000000  ...  462.000000  462.000000  462.000000
mean    31.903282    3.635649    4.740325  ...   17.044394   42.816017    0.346320
std     17.518220    4.593024    2.070909  ...   24.481059   14.608956    0.476313
min      0.000000    0.000000    0.980000  ...    0.000000   15.000000    0.000000
25%     19.658120    0.052500    3.282500  ...    0.510000   31.000000    0.000000
50%     28.205128    2.000000    4.340000  ...    7.510000   45.000000    0.000000
75%     40.170940    5.500000    5.790000  ...   23.892500   55.000000    1.000000
max    100.000000   31.200000   15.330000  ...  147.190000   64.000000    1.000000

[8 rows x 10 columns]

In [14]:
data.head(50).plot(kind='area',figsize=(10,5))

<IPython.core.display.Javascript object>

In [0]:
#Distribution of Obesity according to the age

In [15]:
data.plot(x='age',y='obesity',kind='scatter',figsize =(10,5))

<IPython.core.display.Javascript object>

In [0]:
#Distribution of Tobacco consumption across age

In [16]:
data.plot(x='age',y='tobacco',kind='scatter',figsize =(10,5))

<IPython.core.display.Javascript object>

In [0]:
#Distribution of Alcohol consumption across age

In [17]:
data.plot(x='age',y='alcohol',kind='scatter',figsize =(10,5))

<IPython.core.display.Javascript object>

In [0]:
#Histogram of various freatures in DataFrame

In [18]:
data.plot(kind = 'hist',figsize =(10,5))

<IPython.core.display.Javascript object>

In [0]:
color = dict(boxes='DarkGreen', whiskers='DarkOrange',medians='DarkBlue', caps='Gray')

In [20]:
data.plot(kind='box',figsize=(10,6),color=color,ylim=[-10,90])


<IPython.core.display.Javascript object>

In [0]:
# splitting the data into test and train  having a test size of 20% and 80% train size
from sklearn.model_selection import train_test_split
col = ['sbp','tobacco','ldl','adiposity','famhist','type','obesity','alcohol','age']
X_train, X_test, y_train, y_test = train_test_split(data[col], data['chd'], test_size=0.2, random_state=1234)

In [0]:
#Now, the results of the model does depends on the random state 
#on which we distribute the data, 
#since it's too small data the model understand relative pattern with given test set at random state 42, we obtain results as SVM,ANN and lest with KNN at random state 1234, we obtain results as ANN,SVM and least with KNN

#To overcome this issue, 
# used K-fold too, to increase the accuracy, 
#which gives much higher accuracy as the fold increase and 
#a small increase in mean accuracy too.

#Heatmap Of the realtion features

In [22]:
sns.set()
sns.heatmap(X_train.head(10),robust = True)

In [0]:
X_all = data[col]
y_all = data['chd']


In [0]:
#A Support Vector Machine (SVM) is a discriminative classifier formally defined by a separating hyperplane. In other words, given labeled training data (supervised learning), the algorithm outputs an optimal hyperplane which categorizes new examples.
#Description : https://en.wikipedia.org/wiki/Support_vector_machine
#Kernel used : Linear
#Degree =3
#Gamma = Auto

In [0]:
from sklearn import svm
svm_clf = svm.SVC(kernel ='linear')

In [25]:
svm_clf.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred_svm =svm_clf.predict(X_test)

In [27]:
y_pred_svm

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0])

In [28]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_svm = confusion_matrix(y_test, y_pred_svm)
cm_svm

array([[51,  9],
       [15, 18]])

In [29]:
from sklearn.metrics import accuracy_score
svm_result = accuracy_score(y_test,y_pred_svm)
print("Accuracy :",svm_result)

Accuracy : 0.7419354838709677


In [30]:
recall_svm = cm_svm[0][0]/(cm_svm[0][0] + cm_svm[0][1])
precision_svm = cm_svm[0][0]/(cm_svm[0][0]+cm_svm[1][1])
recall_svm,precision_svm

(0.85, 0.7391304347826086)

In [0]:
#Accuracy : 0.741
#Recall : 0.85
#Precision : 0.739

In [0]:
#In pattern recognition, 
#the k-nearest neighbors algorithm (k-NN) is 
#a non-parametric method used for classification and regression. 
#In both cases, the input consists of the k closest training examples 
#in the feature space. ... In k-NN classification, the output is a class membership.

#Description : https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm
#Neighbors =5
#N jobs = No of cores ,-1
#Leaf size =60
#Algorithm = Brute

In [0]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors =5,n_jobs = -1,leaf_size = 60,algorithm='brute')

In [32]:
knn_clf.fit(X_train,y_train)

KNeighborsClassifier(algorithm='brute', leaf_size=60, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')

In [33]:
y_pred_knn = knn_clf.predict(X_test)
y_pred_knn

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0])

In [34]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_knn = confusion_matrix(y_test, y_pred_knn)
cm_knn

array([[49, 11],
       [22, 11]])

In [35]:
knn_result = accuracy_score(y_test,y_pred_knn)
knn_result

0.6451612903225806

In [36]:
recall_knn = cm_knn[0][0]/(cm_knn[0][0] + cm_knn[0][1])
precision_knn = cm_knn[0][0]/(cm_knn[0][0]+cm_knn[1][1])
recall_knn,precision_knn

(0.8166666666666667, 0.8166666666666667)

In [0]:
#Accuracy : 0.645
#Recall : 0.816
#Precision : 0.816

In [0]:
#Cross Validation recovers from the random state difference 
#by diving the complete data set in K parts, and iteratively learns from data.

#Folds =10

In [37]:
from sklearn.cross_validation import KFold

fold_list =[]
accuracy_list =[]
def run_kfold(knn_clf):
    kf = KFold(297, n_folds=10)
    outcomes = []
    fold = 0
    for train_index, test_index in kf:
        fold += 1
        X_train, X_test = X_all.values[train_index], X_all.values[test_index]
        y_train, y_test = y_all.values[train_index], y_all.values[test_index]
        knn_clf.fit(X_train, y_train)
        predictions = knn_clf.predict(X_test)
        accuracy = accuracy_score(y_test, predictions)
        outcomes.append(accuracy)
        print("Fold {0} accuracy: {1}".format(fold, accuracy))
        fold_list.append(fold)
        accuracy_list.append(accuracy)
        mean_outcome = np.mean(outcomes)
        print("Mean Accuracy: {0}".format(mean_outcome)) 

run_kfold(knn_clf)

ModuleNotFoundError: ignored

In [0]:
#Box plot of the iterative learning by K Fold in K-Nearest Neighbors

In [38]:
fold_df =pd.DataFrame({'Fold':fold_list,'Accuracy':accuracy_list}).set_index('Fold')
fold_df.plot(kind='box',figsize=(4,6),color=color)

NameError: ignored

In [0]:
#Fold 10 accuracy: 0.7586206896551724
#Mean Accuracy: 0.6501149425287356

In [0]:
#MODEL 3 - ANN Multilayer Perceptron Classifier

In [0]:
#Input nodes : 9
#Hidden layers :2
#Each hidden Layer Hold 14 neuron
#Output layer : 2

In [0]:
from sklearn.metrics import make_scorer, accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier

In [0]:
ann_clf = MLPClassifier()

#Parameters
parameters = {'solver': ['lbfgs'],
             'alpha':[1e-4],
             'hidden_layer_sizes':(9,14,14,2),   # 9 input, 14-14 neuron in 2 layers,1 output layer
             'random_state': [1]}

In [41]:
# Type of scoring to compare parameter combos 
acc_scorer = make_scorer(accuracy_score)

# Run grid search 
grid_obj = GridSearchCV(ann_clf, parameters, scoring=acc_scorer)
grid_obj = grid_obj.fit(X_train, y_train)

# Pick the best combination of parameters
ann_clf = grid_obj.best_estimator_

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

I

In [42]:
# Fit the best algorithm to the data 
ann_clf.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=14, learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [0]:
y_pred_ann = ann_clf.predict(X_test)

In [44]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_ann = confusion_matrix(y_test, y_pred_ann)
cm_ann

array([[60,  0],
       [33,  0]])

In [45]:
ann_result = accuracy_score(y_test,y_pred_ann)
ann_result

0.6451612903225806

In [46]:
recall_ann = cm_ann[0][0]/(cm_ann[0][0] + cm_ann[0][1])
precision_ann = cm_ann[0][0]/(cm_ann[0][0]+cm_ann[1][1])
recall_ann,precision_ann

(1.0, 1.0)

In [0]:
#Accuracy : 0.763
#Recall : 0.866
#Precision : 0.732

In [0]:
#Sequential Model Input node :9 Hidden layer :2 Each layer hold 6 neuron

In [47]:
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 9))

# Adding the second hidden layer
#classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_annk = confusion_matrix(y_test, y_pred)


Using TensorFlow backend.







Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=9, units=6, kernel_initializer="uniform")`
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  from ipykernel import kernelapp as app
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:21: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.





Epoch 1/100





369/369 [==============================] - 1s 2ms/step - loss: 0.6676 - acc: 0.6558
Epoch 2/100
369/369 [==============================] - 0s 111us/step - loss: 0.6572 - acc: 0.6558
Epoch 3/100
369/369 [==============================] - 0s 119us/step - loss: 0.6520 - acc: 0.6558
Epoch 4/100
369/369 [==============================] - 0s 195us/step - loss: 0.6436 - acc: 0.6558
Epoch 5/100
369/369 [==============================] - 0s 134us/step - loss: 0.6390 - acc: 0.6612
Epoch 6/100
369/369 [==============================] - 0s 135us/step - loss: 0.6329 - acc: 0.6667
Epoch 7/100
369/369 [==============================] - 0s 128us/step - loss: 0.6244 - acc: 0.6531
Epoch 8/100
369/369 [==============================] - 0s 136us/step - loss: 0.6198 - acc: 0.6558
Epoch 9/100
369/369 [==============================] - 0s 139us/step - loss: 0.6147 - acc: 0.6612
Epoch 10/100
369/369 [==============================] - 0s 129us/step - loss: 0.6082 - acc: 0.6612
Epoch 11/100


In [48]:
cm_annk

array([[53,  7],
       [17, 16]])

In [49]:
recall_annk = cm_annk[0][0]/(cm_annk[0][0] + cm_annk[0][1])
precision_annk = cm_annk[0][0]/(cm_annk[0][0]+cm_annk[1][1])
recall_annk,precision_annk

(0.8833333333333333, 0.7681159420289855)

In [0]:
#Accuracy ~ 0.7317
#Recall : 0.883
#Precision : 0.768

In [0]:
#Comparison of models

In [0]:
results ={'Accuracy': [svm_result*100,knn_result*100,ann_result*100],
          'Recall': [recall_svm*100,recall_knn*100,recall_ann*100],
          'Precision': [precision_svm*100,precision_knn*100,precision_ann*100]}
index = ['SVM','KNN','ANN']

In [0]:
results =pd.DataFrame(results,index=index)

In [52]:
fig =results.plot(kind='bar',title='Comaprison of models',figsize =(9,9)).get_figure()
fig.savefig('Final Result.png')

<IPython.core.display.Javascript object>

In [53]:
fig =results.plot(kind='bar',title='Comaprison of models',figsize =(6,6),ylim=[50,100]).get_figure()
fig.savefig('image.png')

<IPython.core.display.Javascript object>

In [54]:
results.plot(subplots=True,kind ='bar',figsize=(4,10))

<IPython.core.display.Javascript object>

array([<matplotlib.axes._subplots.AxesSubplot object at 0x7fe56d404b38>,
      dtype=object)

In [55]:
Saving graph images
DataFrame
fig = class_counts.plot().get_figure()
fig.savefig('image.png')

SyntaxError: ignored